version: '4.1'

services:
  postgres:
    image: postgres:16
    container_name: challenge_postgres
    restart: always
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: challenge_user
      POSTGRES_PASSWORD: sua_senha_segura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: